apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: gitops-operator-install
  namespace: acm-policies
spec:
  complianceType: musthave        
  remediationAction: enforce
  severity: medium                
  subscription:
    name: openshift-gitops-operator
    namespace: openshift-operators
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    channel: latest               
  upgradeApproval: Automatic
  removalBehavior:
    subscriptions: Delete
    clusterServiceVersions: Delete
    customResourceDefinitions: Delete
    operatorGroups: DeleteIfUnused
  complianceConfig:
    catalogSourceUnhealthy: NonCompliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
