apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Recurso ya creado a mano (Placement)
resources:
  - ../../governance/placements/placement-prod.yaml

# Generador de Policies (Policy, PolicySet, PlacementBinding)
generators:
  - ./generator.yml
